"""Shared financial constants."""

DEFAULT_CURRENCY = "CLP"
DAILY_MARKET_RATE_CODES = ("USD", "EUR", "UF")
MONTHLY_MARKET_RATE_CODES = ("UTM",)
MONTHLY_ECONOMIC_INDEX_CODES = ("IPC_CL",)
MONTHLY_EXCHANGE_RATE_CODES = frozenset(MONTHLY_MARKET_RATE_CODES)
